services:

  backend:
    build:
      context: ${BACK_HOST}
    working_dir: /var/www/backend
    volumes:
      - ${BACK_HOST}:/var/www/backend
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    command:
      sh -c "
      php artisan migrate --force &&
      php artisan storage:link &&
      php-fpm
      "

  frontend:
    build:
      context: ${FRONT_HOST}
    ports:
      - "5173:5173"
    volumes:
      - ${FRONT_HOST}:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${BACK_HOST}:/var/www/backend
      - ${FRONT_HOST}/dist:/var/www/frontend/dist
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  db:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: studies
    ports:
      - "3306:3306"
    volumes:
      - ${DB_HOST}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass
    depends_on:
      - db

  queue:
    build:
      context: ${BACK_HOST}
    restart: unless-stopped
    working_dir: ${APP_CONTAINER}
    volumes:
      - ${BACK_HOST}:${APP_CONTAINER}
    depends_on:
      - db
    command: sh -c "php artisan queue:work --timeout=3600"